### PR TITLE
CLI can now parse scientific notation integers

### PR DESCRIPTION
**Pull request by lobis**
lobis Ok: 20 [](https://gitlab.cern.ch/rest-for-physics/restG4/-/commits/lobis-cli) [](https://gitlab.cern.ch/rest-for-physics/geant4lib/-/commits/lobis-cli) [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/lobis-cli) [](https://github.com/rest-for-physics/restG4/commits/lobis-cli)

Now you can pass values such as `-n 1E5` etc to the CLI and it will be correctly interpreted. It is supported both for the `-n` and `-e` option.

### CODE REVIEW

**Comment by jgalan** [comment]
Don't understand too much the description, could you give an illustrative example?

**Comment by lobis** [comment]
> Don't understand too much the description, could you give an illustrative example?

You can use `restG4 -n 1E4` instead of  `restG4 -n 10000` for instance.

**Review by KonradAltenmueller — APPROVED** [review]

**Comment by jgalan** [comment]
Ok, because sometime ago we discussed about the potential to use `resG4` or `restManager` command line to modify any parameter given at the RML in a generic way. Something like:

```
restG4 --TRestGeant4Metadata::fNevents=1000 --TRestGeant4Metadata::fGDMLFilename=geometry/setup.gdml
```

**Comment by lobis** [comment]
> Ok, because sometime ago we discussed about the potential to use `resG4` or `restManager` command line to modify any parameter given at the RML in a generic way. Something like:
> 
> ```
> restG4 --TRestGeant4Metadata::fNevents=1000 --TRestGeant4Metadata::fGDMLFilename=geometry/setup.gdml
> ```

Yes that would be nice, but I still think it would be nice to have shortcuts for most used parameters such as `-n`

**Pull request merged**
