### PR TITLE
add new cosmic generator

### PR DESCRIPTION
**Pull request by lobis**
lobis Medium: 240 [](https://gitlab.cern.ch/rest-for-physics/restG4/-/commits/lobis-cosmic-generator) [](https://gitlab.cern.ch/rest-for-physics/geant4lib/-/commits/lobis-cosmic-generator) [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/lobis-cosmic-generator) [](https://github.com/rest-for-physics/restG4/commits/lobis-cosmic-generator)

This adds a new type of generator `cosmic` that does not require any parameters. It generates primaries from a sphere surrounding the world volume with the distributions specified in the source. It should produce accurate results "equivalent" to the infinite plane source, but with much faster computation time. (Actually the results will not be the same, because the infinite plane approach is not correctly implemented, there are geometric effects not taken into account, this should be physically accurate).

- https://github.com/rest-for-physics/geant4lib/pull/74

### CODE REVIEW

**Comment by lobis** [comment]
@jgalan there is a very wierd behaviour I have not been able to pinpoint, could you take a look please?

The new generator works correctly with `geantino`, but if you use another particle such as `neutron` or `mu-`, it will fault, something to do with the geant4 particle tables... I tried loading them explicitly but could not. I have no idea what's going on.

To reproduce, just launch the new example with a different particle than a `geantino` , hope its some silly mistake I did not see🤞🏻 , otherwise this PR is ready to go.

**Review by jgalan — COMMENTED** [review]
Plz, update the `TRestGeant4Metadata` documentation adding the new COSMIC generator description.

**Comment by jgalan** [comment]
> @jgalan there is a very wierd behaviour I have not been able to pinpoint, could you take a look please?
> 
> The new generator works correctly with `geantino`, but if you use another particle such as `neutron` or `mu-`, it will fault, something to do with the geant4 particle tables... I tried loading them explicitly but could not. I have no idea what's going on.
> 
> To reproduce, just launch the new example with a different particle than a `geantino` , hope its some silly mistake I did not see🤞🏻 , otherwise this PR is ready to go.

It works also with `e-`, I imagine it works with those at the first list shown in this site: http://fismed.ciemat.es/GAMOS/GAMOS_doc/GAMOS.5.1.0/x11519.html

**Comment by lobis** [comment]
> > @jgalan there is a very wierd behaviour I have not been able to pinpoint, could you take a look please?
> > The new generator works correctly with `geantino`, but if you use another particle such as `neutron` or `mu-`, it will fault, something to do with the geant4 particle tables... I tried loading them explicitly but could not. I have no idea what's going on.
> > To reproduce, just launch the new example with a different particle than a `geantino` , hope its some silly mistake I did not see🤞🏻 , otherwise this PR is ready to go.
> 
> It works also with `e-`, I imagine it works with those at the first list shown in this site: http://fismed.ciemat.es/GAMOS/GAMOS_doc/GAMOS.5.1.0/x11519.html

Interesting, I wonder why that is... 🤔 . I tried a bunch of different ways to import the appropiate headers, event importing directly the headers fo the particle `#include <G4Neutron.hh>` does not fix this...

**Review by juanangp — APPROVED** [review]

**Pull request merged**
