### PR TITLE
Partial changes from `restGeant4` parallel project

### PR DESCRIPTION
**Pull request by lobis**
Large lobis  [](https://gitlab.cern.ch/rest-for-physics/restg4/-/commits/lobis-major-update)

I will be incorporating the major changes in https://github.com/rest-for-physics/restGeant4, in order to avoid having a parallel project.

I will try to the best of my ability to keep the current functionality working (based mostly on the examples in the pipeline). I will also remove some functionality that I think is clearly obsolete / never used anymore.

This https://github.com/rest-for-physics/restG4/issues/20 issue is the place to discuss all changes

### CODE REVIEW

**Comment by lobis** [comment]
@rest-for-physics/restg4 @jgalan do you agree with the renaming of files in https://github.com/rest-for-physics/restG4/pull/19/commits/1741ef348a71424fcbe7507d130c2c18787adf42? I think it is better to use the same style convention for all files across REST. (personally I prefer .cpp vs .cxx but this is another topic)

**Comment by jgalan** [comment]
I suggest that as soon as it passes the pipeline we merge it to master. The changes are mainly of formatting. Then, you may start a new PR to include other changes. It will be easier to track the changes.

**Review by lobis — COMMENTED** [review]
not sure why this is changed? can you explain @jgalan ?

This just define a preprocessor directive `WITHOUT_G4RunManagerFactory` which then you can check in the code to include a header or not, why add the `-D`?

**Comment by jgalan** [comment]
> not sure why this is changed? can you explain @jgalan ?
> 
> This just define a preprocessor directive `WITHOUT_G4RunManagerFactory` which then you can check in the code to include a header or not, why add the `-D`?

This is because previous `cmake` versions do not implement the function `add_compile_definitions(DEFINITION)`, then, I switched to the one used in previous versions, see also stackoverflow link above.

So, the analogue is using `add_definitions(-DDEFINITION)`. It changes nothing, just a different way to write it.

**Comment by lobis** [comment]
> I suggest that as soon as it passes the pipeline we merge it to master. The changes are mainly of formatting. Then, you may start a new PR to include other changes. It will be easier to track the changes. Try to prepare as many PR as possible in the task to merge `restGeant4`



> I suggest that as soon as it passes the pipeline we merge it to master. The changes are mainly of formatting. Then, you may start a new PR to include other changes. It will be easier to track the changes. Try to prepare as many PR as possible in the task to merge `restGeant4`

I have created this https://github.com/rest-for-physics/restG4/issues/20 to track changes

**Comment by lobis** [comment]
Since I have modified many files for style reasons, I think its best to merge this pull request and continue the work of #20 is other pull request

**Review by jgalan — APPROVED** [review]
This is formatting and improvement of command line parsing at restG4.

I would merge these changes already to master in favor of creating shorter PRs.

**Comment by jgalan** [comment]
I will track changes introduced to the code, rather than comments at the issue, so it is better that we keep PRs to minimal contributions to the code.

I have already reviewed the changes introduced and the pipeline is passing. So, it is better to merge and review a different PR. That will facilitate the review process.

**Review by nkx111 — APPROVED** [review]

**Pull request merged**
